### ISSUE TITLE
Dynamic Key-value Memory Enhanced Multi-step Graph Reasoning for Knowledge-based Visual Question Answering

### ISSUE THREAD

**Issue by codewithFlycat** [Mingxiao-Li/Modeling-Coreference-Relations-in-Visual-Dialog#1]
你好
请问 Dynamic Key-value Memory Enhanced Multi-step Graph Reasoning for
Knowledge-based Visual Question Answering 这篇文章的github连接是撤下去了吗

**Comment by Mingxiao-Li** [comment]
你好， 我正在修正文章的格式，修完了 整下代码 就发出来。
